[tool.poetry]
name = "endp"
version = "0.1.0"
description = "this is an endpouint tutorials"
authors = ["liu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
